
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ENDL EPS EQ NON_TERM START TERM UNIONtoken : TERMtoken : NON_TERMtoken : EPStokens : tokentokens : tokens tokenunion : tokensunion : union UNION tokensrule : NON_TERM EQ union ENDLstart : START'
    
_lr_action_items = {'TERM':([0,],[2,]),'NON_TERM':([0,],[3,]),'EPS':([0,],[4,]),'$end':([1,2,3,4,],[0,-1,-2,-3,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'token':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> token","S'",1,None,None,None),
  ('token -> TERM','token',1,'p_token_term','parse.py',43),
  ('token -> NON_TERM','token',1,'p_token_non_term','parse.py',49),
  ('token -> EPS','token',1,'p_token_eps','parse.py',55),
  ('tokens -> token','tokens',1,'p_tokens_token','parse.py',60),
  ('tokens -> tokens token','tokens',2,'p_tokens_tokens_token','parse.py',65),
  ('union -> tokens','union',1,'p_union_tokens','parse.py',70),
  ('union -> union UNION tokens','union',3,'p_union_union_tokens','parse.py',75),
  ('rule -> NON_TERM EQ union ENDL','rule',4,'p_rule','parse.py',80),
  ('start -> START','start',1,'p_start_start','parse.py',86),
]
