
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'EPS NONTERM SEPARATOR START TERM TOtoken : TERMtoken : NONTERMtoken : EPStoken : START SEPARATORmult_tokens : tokenmult_tokens : mult_tokens tokenexpr : START SEPARATORexpr : rule SEPARATORrule : mult_tokens TO mult_tokens'
    
_lr_action_items = {'TERM':([0,],[2,]),'NONTERM':([0,],[3,]),'EPS':([0,],[4,]),'START':([0,],[5,]),'$end':([1,2,3,4,6,],[0,-1,-2,-3,-4,]),'SEPARATOR':([5,],[6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'token':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> token","S'",1,None,None,None),
  ('token -> TERM','token',1,'p_token_term','parse.py',48),
  ('token -> NONTERM','token',1,'p_token_NONTERM','parse.py',54),
  ('token -> EPS','token',1,'p_token_eps','parse.py',60),
  ('token -> START SEPARATOR','token',2,'p_token_start','parse.py',65),
  ('mult_tokens -> token','mult_tokens',1,'p_mtokens_token','parse.py',73),
  ('mult_tokens -> mult_tokens token','mult_tokens',2,'p_mtokens_mtokens_token','parse.py',78),
  ('expr -> START SEPARATOR','expr',2,'p_expr_start','parse.py',83),
  ('expr -> rule SEPARATOR','expr',2,'p_expr_rule','parse.py',89),
  ('rule -> mult_tokens TO mult_tokens','rule',3,'p_rule','parse.py',95),
]
