
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'EPS ID NONTERM SEPARATOR START TERM TOexpr : START SEPARATORexpr : rule SEPARATORrule : mult_tokens TO mult_tokensmult_tokens : tokenmult_tokens : mult_tokens tokentoken : TERMtoken : NONTERMtoken : EPS'
    
_lr_action_items = {'START':([0,],[2,]),'TERM':([0,4,5,6,7,8,11,12,13,],[6,6,-4,-6,-7,-8,6,-5,6,]),'NONTERM':([0,4,5,6,7,8,11,12,13,],[7,7,-4,-6,-7,-8,7,-5,7,]),'EPS':([0,4,5,6,7,8,11,12,13,],[8,8,-4,-6,-7,-8,8,-5,8,]),'$end':([1,9,10,],[0,-1,-2,]),'SEPARATOR':([2,3,5,6,7,8,12,13,],[9,10,-4,-6,-7,-8,-5,-3,]),'TO':([4,5,6,7,8,12,],[11,-4,-6,-7,-8,-5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expr':([0,],[1,]),'rule':([0,],[3,]),'mult_tokens':([0,11,],[4,13,]),'token':([0,4,11,13,],[5,12,5,12,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expr","S'",1,None,None,None),
  ('expr -> START SEPARATOR','expr',2,'p_expr_start','parse.py',53),
  ('expr -> rule SEPARATOR','expr',2,'p_expr_rule','parse.py',61),
  ('rule -> mult_tokens TO mult_tokens','rule',3,'p_rule','parse.py',66),
  ('mult_tokens -> token','mult_tokens',1,'p_mtokens_token','parse.py',71),
  ('mult_tokens -> mult_tokens token','mult_tokens',2,'p_mtokens_mtokens_token','parse.py',76),
  ('token -> TERM','token',1,'p_token_term','parse.py',80),
  ('token -> NONTERM','token',1,'p_token_NONTERM','parse.py',86),
  ('token -> EPS','token',1,'p_token_eps','parse.py',92),
]
