name:                parsing-with-derivatives
version:             0.1.0.0
github:              "kajigor/parsing-with-derivatives"
license:             BSD3
author:              "Ekaterina Verbitskaia"
maintainer:          "kajigor@gmail.com"
copyright:           "Ekaterina Verbitskaia"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://https://github.com/kajigor/fl-2020-hse-win>

dependencies:
- base >= 4.7 && < 5
- hedgehog
- HUnit
- tasty
- tasty-hedgehog
- tasty-hunit
- tasty-discover
- pretty-show
- containers

library:
  source-dirs: src

tests:
  test:
    main:                Test.hs
    source-dirs:         test
    dependencies:
    - parsing-with-derivatives